// Generated at compile time: 2026-07-30T23:52:32.482Z
// DO NOT EDIT THIS FILE MANUALLY - Generated by scripts/embed-api-keys.js

/**
 * Embedded API Constants
 * These are embedded at compile time for production builds
 */

// Embedded API Keys
export const EMBEDDED_OPENSUBTITLES_API_KEY = '';

// Build information
export const BUILD_TIMESTAMP = '2026-07-30T23:52:32.482Z';
export const HAS_EMBEDDED_KEYS = false;

// Validation
export const validateEmbeddedKeys = () => {
  const errors = [];
  
  if (!EMBEDDED_OPENSUBTITLES_API_KEY) {
    errors.push('OpenSubtitles API key not embedded at compile time');
  }
  
  return {
    isValid: errors.length === 0,
    errors,
    hasEmbeddedKeys: HAS_EMBEDDED_KEYS
  };
};

// Get embedded API key with fallback
export const getEmbeddedApiKey = () => {
  return EMBEDDED_OPENSUBTITLES_API_KEY || '';
};

console.log('📦 Embedded constants loaded:', {
  hasApiKey: !!EMBEDDED_OPENSUBTITLES_API_KEY,
  apiKeyPreview: EMBEDDED_OPENSUBTITLES_API_KEY ? 
    (EMBEDDED_OPENSUBTITLES_API_KEY.slice(0,4) + '****' + EMBEDDED_OPENSUBTITLES_API_KEY.slice(-4)) : 
    '[NONE]',
  buildTime: BUILD_TIMESTAMP
});
