// Generated at compile time: 2025-07-23T02:56:13.981Z
// DO NOT EDIT THIS FILE MANUALLY - Generated by scripts/embed-api-keys.js

/**
 * Embedded API Constants
 * These are embedded at compile time for production builds
 */

// Embedded API Keys
export const EMBEDDED_OPENSUBTITLES_API_KEY = '';

// Build information
export const BUILD_TIMESTAMP = '2025-07-23T02:56:13.981Z';
export const HAS_EMBEDDED_KEYS = false;

// Validation
export const validateEmbeddedKeys = () => {
  const errors = [];
  
  if (!EMBEDDED_OPENSUBTITLES_API_KEY) {
    errors.push('OpenSubtitles API key not embedded at compile time');
  }
  
  return {
    isValid: errors.length === 0,
    errors,
    hasEmbeddedKeys: HAS_EMBEDDED_KEYS
  };
};

// Get embedded API key with fallback
export const getEmbeddedApiKey = () => {
  return EMBEDDED_OPENSUBTITLES_API_KEY || '';
};

console.log('📦 Embedded constants loaded:', {
  hasApiKey: !!EMBEDDED_OPENSUBTITLES_API_KEY,
  buildTime: BUILD_TIMESTAMP
});
