name: Test Desktop Build

on:
  workflow_dispatch:

jobs:
  test-ubuntu-build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ubuntu-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Build the app
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          uploadReleaseAssets: false

      - name: Check build artifacts
        run: |
          echo "Build completed successfully!"
          ls -la src-tauri/target/release/bundle/